# تفعيل دعم مكتبات AndroidX الأساسية
android.useAndroidX=true

# تخصيص ذاكرة ممتازة لسرعة البناء المستقرة
org.gradle.jvmargs=-Xmx3076m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError

# تفعيل البناء المتوازي والكاش لتسريع الوقت لأقصى درجة
org.gradle.parallel=true
org.gradle.caching=true

# تفعيل البناء التراكمي لكوتلن (يعمل الآن بشكل مثالي لأن الأقراص توحدت)
kotlin.incremental=true
kotlin.incremental.android=true

# الإعدادات الافتراضية المضافة بواسطة فلاتر
android.builtInKotlin=false
android.newDsl=false